<?php
header('Content-Type: text/html; charset=utf-8');
echo "<pre>";

$data = Array();

// ------------------------------------------
// Atlasdata nimet

$breedingData = file_get_contents("data/atlas3-breeding-data.txt");

$breedingDataArr = explode("\n", $breedingData);

foreach ($breedingDataArr as $number => $row)
{
	$row = trim($row);
	$cells = explode("\t", $row);

	print_r ($cells);

/*
	$sci = $cells[1];

	$data[$sci]['sci'] = $cells[1];
	$data[$sci]['fi'] = $cells[2];
	$data[$sci]['sv'] = $cells[3];
	$data[$sci]['en'] = $cells[4];
	$data[$sci]['abbr'] = $cells[0];

	$data[$sci]['atlas']['julkisuus'] = $cells[5];
*/
}

print_r ($data);

//exit("DEBUG END");


// ------------------------------------------
// Write file

/*
// Remove non-species
foreach ($data as $species => $speciesData)
{
	$removables['SCI'] = 1;
	$removables['Genus Species'] = 1;
	$removables[' '] = 1;

	if (@$removables[$species] == 1 || empty($species))
	{
		unset($data[$species]);
	}
}

$json = json_encode($data);
//file_put_contents("griddata-autogenerated.json", $json);

print_r ($data);
*/

?>

END
