<?php
header('Content-Type: text/html; charset=utf-8');

// This returns a div containing trhe species and grid data
$html = "";

// Todo: security
$grid = $_GET['grid'];
$gridArr = explode(":", $grid);

$speciesArr = getData("speciesdata-autogenerated.json");
$imagesArr = getData("images/speciesimagedata-autogenerated.json");
$gridArr = getData("griddata/" . $gridArr[0] . $gridArr[1] . ".json");


foreach ($gridArr['species'] as $abbr => $singleSpeciesArr)
{
	$speciesHtml = generateSpeciesHtml($abbr);
	echo $speciesHtml;
}



echo "END";

function getData($jsonFilename)
{
	$json = file_get_contents($jsonFilename);
	$dataArr = json_decode($json, TRUE);

//	print_r ($dataArr); // debug

	return $dataArr;
}

function generateSpeciesHtml($abbr)
{
	global $speciesArr;
	global $imagesArr;

	$localHtml = "";

	$fi = $speciesArr[$abbr]['fi'];
	$sci = $speciesArr[$abbr]['sci'];

	$imageUrl = "images/species/200/" . $sci . ".jpg";

	$localHtml .= "
		<h4>$fi ($sci)</h4>
		<img src='$imageUrl' alt='' />
	";

	if ($speciesArr[$abbr]['atlas']['paritKaJarjestys'] > 170)
	{
		$localHtml .= "
			<img src='images/star-green.png'>
		";
	}
	if ($speciesArr[$abbr]['atlas']['ruudutYhtJarjestys'] > 170)
	{
		$localHtml .= "
			<img src='images/star-blue.png'>
		";
	}
	if (@$speciesArr[$abbr]['uhex']['luokka2015'] == "CR")
	{
		$localHtml .= "
			<img src='images/cr.png'>
		";
	}
	if (@$speciesArr[$abbr]['uhex']['luokka2015'] == "EN")
	{
		$localHtml .= "
			<img src='images/en.png'>
		";
	}
	if (@$speciesArr[$abbr]['uhex']['luokka2015'] == "VU")
	{
		$localHtml .= "
			<img src='images/vu.png'>
		";
	}

	return $localHtml;

}

