<?php

// This returns a div containing trhe species and grid data
$html = "";

// Todo: security
$grid = $_GET['grid'];
$gridArr = explode(":", $grid);

$speciesJson = file_get_contents("speciesdata-autogenerated.json");
$imagesJson = file_get_contents("images/speciesimagedata-autogenerated.json");
$gridJson = file_get_contents("griddata/" . $gridArr[0] . $gridArr[1] . ".json");

echo "END";

