<?php
header('Content-Type: text/html; charset=utf-8');

echo "<pre>";

// This returns a div containing trhe species and grid data
$html = "";

// Todo: security
$grid = $_GET['grid'];
$gridArr = explode(":", $grid);

$speciesArr = getData("speciesdata-autogenerated.json");
$imagesArr = getData("images/speciesimagedata-autogenerated.json");
$gridArr = getData("griddata/" . $gridArr[0] . $gridArr[1] . ".json");


echo "END";

function getData($jsonFilename)
{
	$json = file_get_contents($jsonFilename);
	$dataArr = json_decode($json, TRUE);

	print_r ($dataArr); // debug

	return $dataArr;
}


