<?php
header('Content-Type: text/html; charset=utf-8');

$singlespecies = new Singlespecies();



// Class that generates single species HTML

class Singlespecies {

  var $abbr = "";
  var $singleSpeciesDataArr = Array();

  function __construct()
  {
    // Get parameters
    $this->abbr = $_GET['abbr'];

    // Security
    if (strlen($this->abbr) != 6)
    {
      exit("Virheellinen lyhenne");
    }
    echo "täällä"; // debug

    // Get data
    $this->getSpeciesData();

    $this->createHTML();

    print_r ($this->singleSpeciesDataArr); // debug

  }

  function getSpeciesData()
  {
    $allSpeciesDataArr = $this->getJsonData("speciesdata-autogenerated.json");
    $this->singleSpeciesDataArr = $allSpeciesDataArr[$this->abbr];
  }

  // Gets a JSON datafile and decodes it
  function getJsonData($jsonFilename)
  {
    if (! file_exists($jsonFilename))
    {
      return FALSE;
    }

    $json = file_get_contents($jsonFilename);
    $dataArr = json_decode($json, TRUE);

    //  print_r ($dataArr); // debug

    return $dataArr;
  }

  function createHTML()
  {

  }

  // Returns image HTML for a species
  function getImageHtml($sci)
  {
    $imageUrl = "images/species/800/" . $sci . ".jpg";
    return "  <span class='speciesImage'><img src='$imageUrl' alt='' /></span>\n";
  }



} // end of class
