<?php
header('Content-Type: text/html; charset=utf-8');

$singlespecies = new Singlespecies();



// Class that generates single species HTML

class Singlespecies {

  var $abbr = "";
  var $html = "";
  var $singleSpeciesDataArr = Array();

  function __construct()
  {
    // Get parameters
    $this->abbr = $_GET['abbr'];

    // Security
    if (strlen($this->abbr) != 6)
    {
      exit("Virheellinen lyhenne");
    }

    // Get data
    $this->getSpeciesData();

    $this->createHTML();

//    print_r ($this->singleSpeciesDataArr); // debug

  }

  function getSpeciesData()
  {
    $allSpeciesDataArr = $this->getJsonData("speciesdata-autogenerated.json");
    $this->singleSpeciesDataArr = $allSpeciesDataArr[$this->abbr];
  }

  // Gets a JSON datafile and decodes it
  function getJsonData($jsonFilename)
  {
    if (! file_exists($jsonFilename))
    {
      return FALSE;
    }

    $json = file_get_contents($jsonFilename);
    $dataArr = json_decode($json, TRUE);

    //  print_r ($dataArr); // debug

    return $dataArr;
  }

  function createHTML()
  {
    $this->html .= "<div id='singlespecies' class='modal'>\n";
    $this->html .= $this->getImageHtml($this->singleSpeciesDataArr['sci']);
    $this->html .= "<h4>" . $this->singleSpeciesDataArr['fi'] . "</h4>\n";
    $this->html .= "<h5><em>" . $this->singleSpeciesDataArr['sci'] . "</em> | " . $this->singleSpeciesDataArr['sv'] . " | " . $this->singleSpeciesDataArr['en'] . "</h5>\n";

    if ("CR" == $this->singleSpeciesDataArr['uhex']['luokka2015'])
    {
      $this->html .= "<p id='uhex cr uhanalainen'>Äärimmäisen uhanalainen</p>\n";
    }
    elseif ("EN" == $this->singleSpeciesDataArr['uhex']['luokka2015'])
    {
      $this->html .= "<p id='uhex en uhanalainen'>Erittäinen uhanalainen</p>\n";
    }
    elseif ("VU" == $this->singleSpeciesDataArr['uhex']['luokka2015'])
    {
      $this->html .= "<p id='uhex vu uhanalainen'>Vaarantunut</p>\n";
    }
    elseif ("NT" == $this->singleSpeciesDataArr['uhex']['luokka2015'])
    {
      $this->html .= "<p id='uhex nt'>Silmälläpidettävä</p>\n";
    }    
    else
    {
      $this->html .= "<p id='uhex lc'>Ei uhanalainen</p>\n";
    }

    $this->html .= "<p id='atlas'>Lintuatlaksen mukaan:<br />";
    $this->html .= "Pesiviä pareja keskimäärin " . $this->singleSpeciesDataArr['atlas']['paritKa'] . ", eli on ";
    $this->html .= "Suomen " . $this->singleSpeciesDataArr['atlas']['paritKaJarjestys'] . ". runsaslukuisin lintulaji<br />";
    $this->html .= "Pesii enintään " . $this->singleSpeciesDataArr['atlas']['ruudutYht'] . " ruudussa, eli on ";
    $this->html .= "Suomen " . $this->singleSpeciesDataArr['atlas']['ruudutYhtJarjestys'] . ". laajimmalle levinnyt lintulaji<br />";
    $this->html .= "</p>";


    $this->html .= "</div>\n";

    echo $this->html;
  }

  // Returns image HTML for a species
  function getImageHtml($sci)
  {
    $imageUrl = "images/species/800/" . $sci . ".jpg";
    return "  <span class='largeSpeciesImage'><img src='$imageUrl' alt='' /></span>\n";
  }



} // end of class
