<?php

$imageData = getJsonData("../images/speciesimagedata-autogenerated.json");
$speciesData = getJsonData("../speciesdata-autogenerated.json");
// print_r ($imagedata); // debug

foreach ($speciesData as $abbr => $speciesItem)
{
//	print_r ($speciesItem);
	$sci = @$speciesItem['sci'];
	if (isset($imageData[$sci]))
	{
	echo "<p>
		<a href='" . $imageData[$sci]['url'] . "'>" . $speciesItem['fi'] . "</a>: 
		<a href='" . $imageData[$sci]['authorUrl'] . "'>" . $imageData[$sci]['author'] . "</a>, <a href='" . $imageData[$sci]['license'] . "'>" . $imageData[$sci]['license'] . "</a>
		</p>";
	}

	// "sci":"Parus cyanus","name":"Azure Tit","url":"http:\/\/www.flickr.com\/photos\/yeliseev\/2431158895","author":"Sergey Yeliseev","authorUrl":"http:\/\/www.flickr.com\/people\/yeliseev\/","license":"http:\/\/creativecommons.org\/licenses\/by-nc-nd\/2.0\/"
}


// Gets a JSON datafile and decodes it (COPY from allspecies_calss.php)
function getJsonData($jsonFilename)
{
	if (! file_exists($jsonFilename))
	{
	  return FALSE;
	}

	$json = file_get_contents($jsonFilename);
	$dataArr = json_decode($json, TRUE);

	//  print_r ($dataArr); // debug

	return $dataArr;
}



