<?php

$input = file_get_contents("speciesImages.txt");
$cellDelimiter = "\t";


$output = Array();

$inputArr = explode("\n", $input);

//print_r ($inputArr); exit(); // debug

$i = 0;
foreach ($inputArr as $rownumber => $row)
{
	$row = trim($row);

	// Skip header row
	if (0 == $i)
	{
		$i++;
		continue;
	}
	// Skip empty rows
	if (empty($row))
	{
		continue;
	}

	$cells = explode($cellDelimiter, $row);

	$sci = $cells[0];

	$output[$sci]['sci'] = $cells[0];
	$output[$sci]['name'] = $cells[1];
	$output[$sci]['url'] = $cells[2];
	$output[$sci]['author'] = $cells[3];
	$output[$sci]['authorUrl'] = $cells[4];
	$output[$sci]['license'] = $cells[5];

	$i++;
}

//print_r ($output); exit(); // debug

$json = json_encode($output);
file_put_contents("speciesimagedata-autogenerated.json", $json);

echo "Handled $i rows";